### PR TITLE
BDS Sampler Code

### PR DESCRIPTION
**Pull request by bdeonovic**
Initial commit for BDS. Code only.

### CODE REVIEW

**Comment by brian-j-smith** [comment]
BDS code merged and updated. See the [sampler/bds](https://github.com/brian-j-smith/Mamba.jl/tree/sampler/bds) branch.  We need an example to test the ``bds!`` function and perhaps a Model-based one for the ``BDS`` sampler too...  and documentation.

**Comment by brian-j-smith** [comment]
Is there an advantage to having the number of indices randomly generated in the BDS constructor

```julia
function BDS(params::Vector{Symbol}, d::Integer)
  G = Truncated(Geometric(2 / d), 1, d)
  k = Int(rand(G))
  Γ = collect(combinations([1:d;], k))
  BDS(params, Γ)
end
```
versus a user-specified value

```julia
function BDS(params::Vector{Symbol}, d::Integer, k::Integer=1)
  Γ = collect(combinations([1:d;], k))
  BDS(params, Γ)
end
```
???  The latter is more general in that the user would have the option of specifying a fixed or random value, including the type of randomization employed.

**Comment by bdeonovic** [comment]
Its nice to be able to provide the set of indices which a user wants the sampler to flip together. The user might be able to construct a set (based off other knowledge in the model) that flips variables that are related somehow together. This can lead to more efficient samplers.

**Comment by brian-j-smith** [comment]
I agree that it is desirable to let the user specify a set of indices, but do you want to make a case that the ``BDS`` constructor should randomly pick the number of indices to flip together?  If not, I would like to remove that behavior with the code change noted in my earlier comment because

1. the constructor will be more general if the user explicitly supplies the number to flip;
2. if the constructor's pick leads to poor sampler performance, the package and not the user, is responsible; and
3. the user would be less aware of the number of indices picked by an internal, random routine.

**Pull request merged**
