### PR TITLE
small fixes to tune field management

### PR DESCRIPTION
**Pull request by axsk**
- ~~fixes https://github.com/brian-j-smith/Mamba.jl/issues/66#issuecomment-189545241~~
- enforces type stability of the edited functions

### CODE REVIEW

**Comment by axsk** [comment]
i hope the pr is now equivalent to the original code, just cleaner :)

**Comment by brian-j-smith** [comment]
I really like that the PR now focuses on one self-contained set of changes, and I like how the changes simplify the code.  It does, however, remove support for a ``block`` value of 0, which breaks with the convention used in other simulation functions (logpdf, sample!, unlist, etc.).  I think this PR could be a nice addition to the package if support for a ``block`` value of 0 could be restored, while still maintaining some of the code simplifications.

**Comment by axsk** [comment]
The last commit restored the support for ```block=0```, but is this really necessary?
Reading the code it often felt like encoding the "all" information in a 0 was rather dirty.
It also makes the method type unstable (c.f. [Writing Type-Stable Code in Julia](http://www.johnmyleswhite.com/notebook/2013/12/06/writing-type-stable-code-in-julia)), although that might not be that critical at this point.

I'm fine with this "hackit" but will still look for other solutions :)

**Comment by brian-j-smith** [comment]
Merged.

**Pull request closed without merging**
