### PR TITLE
Individual Adaptation Sampler

### PR DESCRIPTION
**Pull request by bdeonovic**
One more binary sampler.

### CODE REVIEW

**Comment by brian-j-smith** [comment]
Thanks for the new sampler.  I see that the authors call it IA in their manuscript, and hence the IAS name.  However, I think it would be nice if the name started with a 'B' in keeping with the convention used for the other binary samplers.  Prepending a 'B' gives BIAS which I am not totally crazy about since that is an unrelated statistical concept.  Maybe BIA or other ideas if you have them.

**Comment by bdeonovic** [comment]
I think BIA sounds fine.

**Comment by bdeonovic** [comment]
but I think we missed an opportunity to call it "Yet another binary sampler..."

**Comment by brian-j-smith** [comment]
Is there any particular reason that you have the default for epsilon being divided by the length of x (0.01 / length(x)) as opposed to just a constant (0.01)?

**Comment by bdeonovic** [comment]
I asked author for source code and that was default they used.

**Comment by brian-j-smith** [comment]
The sampler is now merged into the master branch and will be in the next package release.

**Pull request closed without merging**
