### PR TITLE
Modify the annotate method to use showoff.

### PR DESCRIPTION
**Pull request by dmbates**
I would prefer that what is now annotate would become a show method.

### CODE REVIEW

**Comment by dmbates** [comment]
See issue #34.

As mentioned in the original comment I would prefer that `annotate` be removed and that this become a `show` method.  Right now `annotate` creates a long string just to turn around and print it in the `show` method.  It is slightly better to write directly to the stream.

The problem right now is the `describe` function (btw, if you are going to use the name "describe" you may want to consider making this a method for `StatsBase.describe`).  It prints information directly to STDOUT which is not a good practice.  Within a package all `print` and `write` methods should take an IO object as the first argument.  Things work fine with this patch if you call `summarystats` or `quantile` directly but not if you go through `describe`.

**Comment by brian-j-smith** [comment]
Thanks on several fronts.  The following are in the develop branch now:

* Your pull with a new `annotate` function is merged in.  Looks really nice.
* The old `annotate` functions have been removed and the new one made a `show` method.
* A `show` method is now defined for the `describe` function to fix the IO issue mentioned.

Let me know if any of the changes are not what you had in mind.

**Comment by brian-j-smith** [comment]
@dmbates:

What do you think of the definition of `describe` given below?  I realize that you said not to write to STDOUT, but that seems to be what the julia base definition of `show(x)` does (used by the describe function in StatsBase).  So, the definition here seems consistent with that behavior.

```julia
describe(c::Chains; args...) = describe(STDOUT, c; args...)

function describe(io::IO, c::Chains; q::Vector=[0.025, 0.25, 0.5, 0.75, 0.975],
                  etype=:bm, args...)
  ps_stats = summarystats(c; etype=etype, args...)
  ps_quantiles = quantile(c, q=q)
  println(io, ps_stats.header)
  print(io, "Empirical Posterior Estimates:\n")
  show(io, ps_stats)
  print(io, "Quantiles:\n")
  show(io, ps_quantiles)
end
```

P.S.  The describe function from StatsBase is imported into Mamba.

**Comment by dmbates** [comment]
That looks fine.  The thing I wanted to avoid was direct calls to `print` or `write` without an `IO` argument.  Using the default IO object for a default method seems okay to me.

**Pull request merged**
