### PR TITLE
Another Example for Slice Simplex

### PR DESCRIPTION
**Pull request by bdeonovic**
Brian, I just noticed you already implemented a model example for the slice simplex. Here is the one I was working on. 

The model involves 4 multinomials basically, with 4 separate probability vectors. I'm not pleased with the way I had to code up the model code and I was wondering if you had a better way of doing it. 

Here are the BUGS results for it:

http://www.mrc-bsu.cam.ac.uk/software/bugs/the-bugs-project-the-bugs-book/bugs-book-examples/the-bugs-book-examples-chapter-7-7-2-1/

(Model description on pg. 127 of the BUGS book: https://books.google.com/books?id=zG7SBQAAQBAJ&lpg=PA130&ots=QvhCmrMLQd&dq=BUGS%20asthma%20example%20dirichlet&pg=PA127#v=onepage&q=BUGS%20asthma%20example%20dirichlet&f=false)

### CODE REVIEW

**Comment by brian-j-smith** [comment]
This will make for a nice SliceSimplex example addition to the package.  Thanks for implementing it.  The one I had done was an existing example with just a two-element probability vector.  The nice thing about this asthma example is that the Dirichlet distributions could be stored in Mamba as a ``Array{MultivariateDistribution}`` in a stochastic node, like they do it in the BUGS implementation.  That would be my suggestion for alternatively coding up the model.  Such an implementation would also be a good/different test case for the SliceSimplex constructor code.

**Comment by bdeonovic** [comment]
Brian, could you check the code on this. I am getting errors but I don't understand why. In particular when I try to 
```julia 
setinits!(model,inits[1])
```
I get 
```julia
ERROR: incompatible stochastic node and distribution structure dimensions
 in setinits! at /home/benjamin/.julia/v0.4/Mamba/src/model/dependent.jl:148
 in setinits! at /home/benjamin/.julia/v0.4/Mamba/src/model/initialization.jl:19
```

**Comment by brian-j-smith** [comment]
In the Dirichlet model node specification below, it looks like the argument should be ``ones(5)`` or ``ones(size(y, 2))``.

```julia
q = Stochastic(2,
     @modelexpr(M,
       MultivariateDistribution[
           Dirichlet(ones(length(M)))
         for i in 1:length(M)
       ]
     ),true
   )
```

**Comment by bdeonovic** [comment]
Good catch, sometimes its just the easiest things that slip by.

**Comment by brian-j-smith** [comment]
P.S.  In case you haven't seen it already, there is a discussion in issue #55 about an alternative syntax for model node specification that may be of interest.

**Comment by bdeonovic** [comment]
Git really gets over my head sometimes -_-

**Comment by bdeonovic** [comment]
Conquered it! I think this is ready to merge whenever you want to merge it.

**Comment by brian-j-smith** [comment]
Thanks!  The example is merged and included in the [latest (0.7.0) release](http://mambajl.readthedocs.org/en/latest/examples/asthma.html).  This release also implements function syntax for the specification of model nodes, as reflected in the updated [tutorial](http://mambajl.readthedocs.org/en/latest/tutorial.html) and [examples](http://mambajl.readthedocs.org/en/latest/examples.html).

**Pull request closed without merging**
